name: focus_body
description: Eine Flutter-App zur Konzentrationssteigerung mit Mikrofonüberwachung, ToDo-Liste und Pomodoro-Timer.

# Die aktuelle Version deiner App
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Mikrofon- und Lärmpegel-Überwachung
  noise_meter: ^5.0.2
  permission_handler: ^11.3.1

  # Lokale Benachrichtigungen
  flutter_local_notifications: ^18.0.1

  # Datenpersistenz
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # UUID für eindeutige IDs
  uuid: ^3.0.7

  # Intl für Datum- und Zeitformatierung
  intl: ^0.18.0

  # Icons und UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive Code Generator (falls du Hive TypeAdapters verwenden möchtest)
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # Assets (falls du Bilder oder andere Assets verwendest)
  assets:
    - assets/images/
    - assets/icons/
